service: imu-mechanization-websocket

provider:
  name: aws
  runtime: python3.8
  region: "us-east-1"
  stage: ${opt:stage, 'dev'}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "execute-api:ManageConnections"
      Resource:
        - "arn:aws:execute-api:us-east-1:028933020796:*/*/POST/@connections/*"


plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    zip: true

package:
  exclude:
    - '**/*'
  include:
    - '*.py'
    - 'numpy'
    - 'scipy'
    - 'AHRS'
    - 'geopy'

functions:
  connectionManager:
    handler: handler.websocket_handler
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
      - websocket:
          route: $default