service: imu-mechanization-websocket

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  region: "us-east-1"

  websocketApiName: my-websocket-api
  stage: ${opt:stage, 'dev'}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "execute-api:ManageConnections"
      Resource:
        - "arn:aws:execute-api:us-east-1:028933020796:*/*/POST/@connections/*"

functions:
  connectionManager:
    handler: handler.connection_manager
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
      - websocket:
          route: $default

package:
  exclude:
    - node_modules/**
    - .venv/**