service: imu-mechanization-websocket

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  apiGateway:
    websocketApiName: my-websocket-api
    websocketApiRouteSelectionExpression: $request.body.action
  websocketApiId:
    Fn::ImportValue:
      !Join ['-', ['my-websocket-api', '${self:provider.stage}', 'WebSocketApiId']]
  iamRoleStatements:
    - Effect: Allow
      Action:
        - execute-api:ManageConnections
      Resource:
        - "arn:aws:execute-api:${self:provider.region}:${self:provider.account}:${self:provider.apiGateway.websocketApiId}/*/@connections/*"
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: "*"

functions:
  websocket:
    handler: handler.websocket_handler
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
      - websocket:
          route: $default
    # Define the list of external libraries here
    pythonRequirements:
      dockerizePip: non-linux
      requirements:
        - requests
        - boto3

resources:
  Resources:
    WebSocketAuthorizer:
      Type: AWS::ApiGatewayV2::Authorizer
      Properties:
        ApiId: ${self:provider.apiGateway.websocketApiId}
        AuthorizerType: REQUEST
        IdentitySource: $request.header.Authorization
        Name: my-websocket-authorizer
        AuthorizerPayloadFormatVersion: '2.0'
        AuthorizerResultTtlInSeconds: 300
        # Define your authorizer function here
        AuthorizerUri: arn:aws:apigateway:${self:provider.region}:lambda:path/2015-03-31/functions/${self:service}-${self:provider.stage}-authorizer:${self:provider.runtime}/invocations
    WebSocketPermission:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName: ${self:service}-${self:provider.stage}-websocket
        Action: lambda:InvokeFunction
        Principal: apigateway.amazonaws.com
        SourceArn: "arn:aws:execute-api:${self:provider.region}:${self:provider.account}:${self:provider.apiGateway.websocketApiId}/*"
