service: imu-mechanization-websocket

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8

functions:
  connect:
    handler: handler.connect
    events:
      - websocket:
          route: $connect
          authorizer:
            arn: arn:aws:execute-api:us-east-1:028933020796:2m72fvzj25/*/$connect
  disconnect:
    handler: handler.disconnect
    events:
      - websocket:
          route: $disconnect
          authorizer:
            arn: arn:aws:execute-api:us-east-1:028933020796:2m72fvzj25/*/$disconnect
  default:
    handler: handler.default
    events:
      - websocket:
          route: $default
          authorizer:
            arn: arn:aws:execute-api:us-east-1:028933020796:2m72fvzj25/*/$default
package:
  exclude:
    - node_modules/**
    - .venv/**