service: imu-mechanization-websocket

provider:
  name: aws
  runtime: python3.8
  region: "us-east-1"
  stage: ${opt:stage, 'dev'}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "execute-api:ManageConnections"
      Resource:
        - "arn:aws:execute-api:us-east-1:028933020796:*/*/POST/@connections/*"

functions:
  connectionManager:
    handler: handler.websocket_handler
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
      - websocket:
          route: $default
custom:
  pythonRequirements:
    zip: true
    dockerizePip: true
plugins:
  - serverless-python-requirements
